### PR TITLE
Enable multiple phrase queries, results must satisfy all criteria

### PR DESCRIPTION
**Pull request by cehsu**
This change is [Reviewable](https://reviewable.io/reviews/sfbrigade/sfsbook/97)

### CODE REVIEW

**Comment by rjkroege** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[dba/query_generator.go, line 73 at r1](https://reviewable.io:443/reviews/sfbrigade/sfsbook/97#-KcW84IrRX0jzRivJtfn:-KcW84IrRX0jzRivJtfo:b-63aeu8) ([raw file](https://github.com/sfbrigade/sfsbook/blob/50f15e87b989914df8ed32f411d01170266a1c49/dba/query_generator.go#L73)):*
> ```Go
> 	// Actually do a query against the database.
> 	// TODO(rjk): Refine the search handling.
> 	middleq := make([]query.Query, 0, 5)
> ```

so the second number in `make(<array>, <length>, <capacity>)` is how much space is reserved for the slice. You'll note that it's exactly the same as the number of strings in the range op. So, with your change below, the 5 should be 7.

---

*[dba/query_generator.go, line 76 at r1](https://reviewable.io:443/reviews/sfbrigade/sfsbook/97#-KcW7t-LIL82X8wd9JCB:-KcW7t-LIL82X8wd9JCC:b-12k7hg) ([raw file](https://github.com/sfbrigade/sfsbook/blob/50f15e87b989914df8ed32f411d01170266a1c49/dba/query_generator.go#L76)):*
> ```Go
> 	phrases := strings.Split(querystring, ", ")
> 	for _, phrase := range phrases {
> 		//  for _, k := range []string{"description", "services", "categories", "name", "website", "email", "address" } {
> ```

Remove commented out code please.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sfbrigade/sfsbook/97)*

**Comment by rjkroege** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[dba/query_generator.go, line 29 at r2](https://reviewable.io:443/reviews/sfbrigade/sfsbook/97#-Kd3xUiBu27Ul1-DmAqw:-Kd3xUiBu27Ul1-DmAqx:b7gih2v) ([raw file](https://github.com/sfbrigade/sfsbook/blob/5afbad79866a418e931ca9cc6465654ffca50cad/dba/query_generator.go#L29)):*
> ```Go
> 	Services    string
> 	Address     string
>   Website     string
> ```

You didn't run `gofmt`?

---

*[dba/query_generator.go, line 128 at r2](https://reviewable.io:443/reviews/sfbrigade/sfsbook/97#-Kd3yQO2IU-EA-Ul7Fit:-Kd3yQO2IU-EA-Ul7Fiu:bqixmca) ([raw file](https://github.com/sfbrigade/sfsbook/blob/5afbad79866a418e931ca9cc6465654ffca50cad/dba/query_generator.go#L128)):*
> ```Go
> 		results.Resources[c].Description = sr.Fields["description"].(string)
> 		results.Resources[c].Address = sr.Fields["address"].(string)
>     results.Resources[c].Website = sr.Fields["website"].(string)
> ```

`gofmt` Please.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sfbrigade/sfsbook/97)*

**Comment by rjkroege** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sfbrigade/sfsbook/97#-:-Kd4Dmx_TA6YvjBWdTuh:bnfp4nl)*

**Comment by rjkroege** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sfbrigade/sfsbook/97#-:-Kd6D8QbX9T6eh-aayf2:bnfp4nl)*

**Comment by cehsu** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[dba/query_generator.go, line 128 at r2](https://reviewable.io:443/reviews/sfbrigade/sfsbook/97#-Kd3yQO2IU-EA-Ul7Fit:-Kd7FuHrJj3Q0K5S86Lo:b-jcr9ao) ([raw file](https://github.com/sfbrigade/sfsbook/blob/5afbad79866a418e931ca9cc6465654ffca50cad/dba/query_generator.go#L128)):*
<details><summary><i>Previously, rjkroege (Robert Kroeger) wrote…</i></summary><blockquote>

`gofmt` Please.
</blockquote></details>

ran it!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sfbrigade/sfsbook/97)*

**Comment by cehsu** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[dba/query_generator.go, line 73 at r1](https://reviewable.io:443/reviews/sfbrigade/sfsbook/97#-KcW84IrRX0jzRivJtfn:-Kd7GmSk1CPd8SqcpGRB:b-2hl98i) ([raw file](https://github.com/sfbrigade/sfsbook/blob/50f15e87b989914df8ed32f411d01170266a1c49/dba/query_generator.go#L73)):*
<details><summary><i>Previously, rjkroege (Robert Kroeger) wrote…</i></summary><blockquote>

so the second number in `make(<array>, <length>, <capacity>)` is how much space is reserved for the slice. You'll note that it's exactly the same as the number of strings in the range op. So, with your change below, the 5 should be 7.
</blockquote></details>

thanks for the pointer, fixed it.

---

*[dba/query_generator.go, line 76 at r1](https://reviewable.io:443/reviews/sfbrigade/sfsbook/97#-KcW7t-LIL82X8wd9JCB:-Kd7Gor2UXBm6wlkemhL:bhgsqjl) ([raw file](https://github.com/sfbrigade/sfsbook/blob/50f15e87b989914df8ed32f411d01170266a1c49/dba/query_generator.go#L76)):*
<details><summary><i>Previously, rjkroege (Robert Kroeger) wrote…</i></summary><blockquote>

Remove commented out code please.
</blockquote></details>

thanks, removed it.

---

*[dba/query_generator.go, line 29 at r2](https://reviewable.io:443/reviews/sfbrigade/sfsbook/97#-Kd3xUiBu27Ul1-DmAqw:-Kd7GhivCtpGo1JCKBVp:bv3crss) ([raw file](https://github.com/sfbrigade/sfsbook/blob/5afbad79866a418e931ca9cc6465654ffca50cad/dba/query_generator.go#L29)):*
<details><summary><i>Previously, rjkroege (Robert Kroeger) wrote…</i></summary><blockquote>

You didn't run `gofmt`?
</blockquote></details>

thanks for the heads up, ran it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sfbrigade/sfsbook/97)*

**Pull request merged**
