### PR TITLE
fixing json fields for business, crisis, and fax lines as well as add…

### LINKED ISSUE #101: provide complete data (phone/fax) for each results
- include phone and fax numbers

### PR DESCRIPTION
**Pull request by mwillcox**
…ing them into the resource page on the frontend

Fixes #101

---
This change is [Reviewable](https://reviewable.io/reviews/sfbrigade/sfsbook/132)

### CODE REVIEW

**Comment by techieshark** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[site/resources/resource.html, line 68 at r1](https://reviewable.io:443/reviews/sfbrigade/sfsbook/132#-Kh4LetvxHrREGWLHRa9:-Kh4LetvxHrREGWLHRaA:b4dv883) ([raw file](https://github.com/sfbrigade/sfsbook/blob/3cc40ad1a120691638267eefa2f7dedd0559412a/site/resources/resource.html#L68)):*
> ```HTML
>           <div class="onefield">
>             <label for="Phone">Business Line</label>
>             <input id="Phone" type="text" name="phone" size="80" value="{{.Document.business_line}}"./>
> ```

We may want to stick with the convention used for other fields, which appears to be `id` with a lowercase name ("phone" not "Phone").

---

*[site/resources/resource.html, line 73 at r1](https://reviewable.io:443/reviews/sfbrigade/sfsbook/132#-Kh4LBlIphsEic88YKjD:-Kh4LBlJgyNnv1MBniVx:b-kjtl6j) ([raw file](https://github.com/sfbrigade/sfsbook/blob/3cc40ad1a120691638267eefa2f7dedd0559412a/site/resources/resource.html#L73)):*
> ```HTML
>           <div class="onefield">
>             <label for="Phone">Crisis Line</label>
>             <input id="Phone" type="text" name="phone" size="80" value="{{.Document.crisis_line}}"./>
> ```

id="Phone" is repeated here. The `id` attribute must be unique in a document (https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id).

---

*[site/resources/resource.html, line 78 at r1](https://reviewable.io:443/reviews/sfbrigade/sfsbook/132#-Kh4LNgwERydzKZ4gCkl:-Kh4LNgwERydzKZ4gCkm:b-kjtl6j) ([raw file](https://github.com/sfbrigade/sfsbook/blob/3cc40ad1a120691638267eefa2f7dedd0559412a/site/resources/resource.html#L78)):*
> ```HTML
>           <div class="onefield">
>             <label for="Phone">Fax</label>
>             <input id="Phone" type="text" name="phone" size="80" value="{{.Document.fax}}"./>
> ```

id="Phone" is repeated here. The `id` attribute must be unique in a document (https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sfbrigade/sfsbook/132)*

**Comment by techieshark** [comment]
BTW @mwillcox the thing that clued me into the fact the database wasn't being initialized with the JSON was noting the difference between the 'broken' install and 'working' (fresh install):

broken, `make start` after `make clean open`:

```
./sfsbook -init_passwords
2017/04/14 10:49:07 sfsbook starting
2017/04/14 10:49:07 hello from setup, creating state in /Users/peter/go/src/github.com/sfbrigade/sfsbook/state
2017/04/14 10:49:07 hello from setup, creating state in /Users/peter/go/src/github.com/sfbrigade/sfsbook/state
```

works: initial make start

```
./sfsbook -init_passwords
2017/04/14 10:43:31 sfsbook starting
2017/04/14 10:43:31 hello from setup, creating state in /Users/peter/go/src/github.com/sfbrigade/sfsbook/state
2017/04/14 10:43:31 hello from setup, creating state in /Users/peter/go/src/github.com/sfbrigade/sfsbook/state
2017/04/14 10:43:31 RefGuideType LoadStartData
2017/04/14 10:43:31 read the database
2017/04/14 10:43:31 parsed the database record
2017/04/14 10:43:31 built a batch
2017/04/14 10:43:38 done Indexing...
2017/04/14 10:43:38 Setting up default password file. Warning! This is not secure. Seriously!
```

Note that when the system works correctly (read the new values from the JSON), it shows these lines:
```
... RefGuideType LoadStartData
2017/04/14 10:43:31 read the database
2017/04/14 10:43:31 parsed the database record
2017/04/14 10:43:31 built a batch
2017/04/14 10:43:38 done Indexing...
```

So then I looked for "RefGuideType LoadStartData" in the code and looked at the code that initialized the database and after a bit of debugging realized that the code wasn't initializing as expected because the database file was actually present.

**Comment by mwillcox** [comment]
*[site/resources/resource.html, line 73 at r1](https://reviewable.io:443/reviews/sfbrigade/sfsbook/132#-Kh4LBlIphsEic88YKjD:-KhmQV_EbsiGSHlHMkll:b-896fja) ([raw file](https://github.com/sfbrigade/sfsbook/blob/3cc40ad1a120691638267eefa2f7dedd0559412a/site/resources/resource.html#L73)):*
<details><summary><i>Previously, techieshark (Peter W) wrote…</i></summary><blockquote>

id="Phone" is repeated here. The `id` attribute must be unique in a document (https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id).
</blockquote></details>

Done!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sfbrigade/sfsbook/132)*

**Comment by mwillcox** [comment]
*[site/resources/resource.html, line 78 at r1](https://reviewable.io:443/reviews/sfbrigade/sfsbook/132#-Kh4LNgwERydzKZ4gCkl:-KhmQpRY4-DTgKSasZdw:b-896fja) ([raw file](https://github.com/sfbrigade/sfsbook/blob/3cc40ad1a120691638267eefa2f7dedd0559412a/site/resources/resource.html#L78)):*
<details><summary><i>Previously, techieshark (Peter W) wrote…</i></summary><blockquote>

id="Phone" is repeated here. The `id` attribute must be unique in a document (https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id).
</blockquote></details>

Done!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sfbrigade/sfsbook/132)*

**Comment by mwillcox** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[site/resources/resource.html, line 68 at r1](https://reviewable.io:443/reviews/sfbrigade/sfsbook/132#-Kh4LetvxHrREGWLHRa9:-Kh8Uu6rYY2kZUQOrcPE:baja9tk) ([raw file](https://github.com/sfbrigade/sfsbook/blob/3cc40ad1a120691638267eefa2f7dedd0559412a/site/resources/resource.html#L68)):*
<details><summary><i>Previously, techieshark (Peter W) wrote…</i></summary><blockquote>

We may want to stick with the convention used for other fields, which appears to be `id` with a lowercase name ("phone" not "Phone").
</blockquote></details>

Good catch! I will update to be consistent with the other fields

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sfbrigade/sfsbook/132)*

**Comment by mwillcox** [comment]
Reviewed 1 of 1 files at r2, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sfbrigade/sfsbook/132)*

**Comment by mwillcox** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sfbrigade/sfsbook/132)*

**Pull request merged**
