### PR TITLE
adds login test (and changes a couple core files as necessary)

### LINKED ISSUE #127: add test for redirect on login
As of PR #125, we redirect to index.html from login (issue #117). 

It was [suggested](https://github.com/sfbrigade/sfsbook/pull/125#issuecomment-289163225) that we add a test for this.

### PR DESCRIPTION
**Pull request by techieshark**
* The point of this commit was just to check that logging in results in a redirect from /login.html to /index.html.
* In order to do so, Search() in dba/password_index.go had to be generalized, which:
  * Fixes TODO in the code: "fix the layering violation of leaking bleve into the interface."
  * affects the code in server/login.go (it uses the general, non bleve, dba.PasswordSearchResult)
* We also had to implement mockPasswordIndex.Search() so the test can run.

Resolves #127

To test this test, run:

```
go get github.com/rjkroege/mocking 
cd server
go test -run TestServeHTTP
```

output should look like this:

```
2017/03/27 14:55:45 login.go:57: loginServer is handling request for /login.html
2017/03/27 14:55:45 login.go:63: handling Post of resource
2017/03/27 14:55:45 login.go:75: parsing form:
2017/03/27 14:55:45 login.go:77: 	 password 		 [password]
2017/03/27 14:55:45 login.go:77: 	 username 		 [test_user]
2017/03/27 14:55:45 login.go:119: username:  test_user has signed in
2017/03/27 14:55:45 login.go:146: usercookie &{28e5c7b9-9f39-4ebc-a9fb-5e7cfffa2687 175 2017-03-27 14:55:45.234172277 -0700 PDT test_user}
2017/03/27 14:55:45 login.go:163: login worked, redirecting to index
2017/03/27 14:55:45 templating.go:95: this is the template /login.html
PASS
ok  	github.com/sfbrigade/sfsbook/server	0.201s
```

---
This change is [Reviewable](https://reviewable.io/reviews/sfbrigade/sfsbook/128)

### CODE REVIEW

**Comment by rjkroege** [comment]
Reviewed 3 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, 11 unresolved discussions.

---

*[dba/password_index.go, line 59 at r1](https://reviewable.io:443/reviews/sfbrigade/sfsbook/128#-KgJSmikTQTzPhJt_-ls:-KgJSmikTQTzPhJt_-lt:b-wexmqg) ([raw file](https://github.com/sfbrigade/sfsbook/blob/62b2c67daab34b13f929eebc6120340f35d5fb72/dba/password_index.go#L59)):*
> ```Go
> // Brought out to simplify mocking.
> type PasswordSearchResult struct {
> 	PasswordHash, Role, DisplayName string
> ```

Given `PasswordMatch()`, could `PasswordHash` be private (i.e. `passwordHash`)?

---

*[dba/password_index.go, line 65 at r1](https://reviewable.io:443/reviews/sfbrigade/sfsbook/128#-KgJT11pcquK5cFGUB0q:-KgJPQkgvMP7S8nReNLZ:bvb2sns) ([raw file](https://github.com/sfbrigade/sfsbook/blob/62b2c67daab34b13f929eebc6120340f35d5fb72/dba/password_index.go#L65)):*
> ```Go
> 
> // PasswordMatch checks if an unencrypted password matches the stored hash.
> func (psr PasswordSearchResult) PasswordMatch(password string) (isMatch bool, err error) {
> ```

I'd probably pass `psr` by reference? (i.e. `*PasswordSearchResult`) as passing it by value makes a temporary. But `PasswordSearchResult` instances aren't very big. So maybe it doesn't matter very much.

---

*[dba/password_index.go, line 68 at r1](https://reviewable.io:443/reviews/sfbrigade/sfsbook/128#-KgJWjjKH-QroHY16B-I:-KgJWjjKH-QroHY16B-J:b2odigv) ([raw file](https://github.com/sfbrigade/sfsbook/blob/62b2c67daab34b13f929eebc6120340f35d5fb72/dba/password_index.go#L68)):*
> ```Go
> 	err = bcrypt.CompareHashAndPassword([]byte(psr.PasswordHash), []byte(password));
> 	// note: bcrypt returns err=nil on success
> 	isMatch = err == nil
> ```

nit: why not just return `err`?

---

*[dba/password_index.go, line 72 at r1](https://reviewable.io:443/reviews/sfbrigade/sfsbook/128#-KgJSK0zVrUr-JuKdUnj:-KgJSK0zVrUr-JuKdUnk:b-t3lsfi) ([raw file](https://github.com/sfbrigade/sfsbook/blob/62b2c67daab34b13f929eebc6120340f35d5fb72/dba/password_index.go#L72)):*
> ```Go
> }
> 
> func (pdoc *blevePasswordIndex) Search(username string) (PasswordSearchResult, error) {
> ```

The code could be more efficient if you returned a `*PasswordSearchResult`. And then `Found` would be unnecessary: simply return nil is nothing was found.

---

*[dba/password_index.go, line 80 at r1](https://reviewable.io:443/reviews/sfbrigade/sfsbook/128#-KgJTMUV32ASgQH8Tmm1:-KgJTMUV32ASgQH8Tmm2:b777y6q) ([raw file](https://github.com/sfbrigade/sfsbook/blob/62b2c67daab34b13f929eebc6120340f35d5fb72/dba/password_index.go#L80)):*
> ```Go
> 	searchResults, err := pdoc.idx.Search(sreq)
> 
> 	result := PasswordSearchResult{}
> ```

This isn't particularly idiomatic. Something more like:

```go
return &PasswordSearchResult {
  // fields initializers...
}
```

is more typical.

---

*[server/login.go, line 111 at r1](https://reviewable.io:443/reviews/sfbrigade/sfsbook/128#-KgJUGN2InyphZ5cpnKB:-KgJUGN2InyphZ5cpnKC:bw95zxn) ([raw file](https://github.com/sfbrigade/sfsbook/blob/62b2c67daab34b13f929eebc6120340f35d5fb72/server/login.go#L111)):*
> ```Go
> 		}
> 
> 		if matchFound, err := searchResults.PasswordMatch(password); matchFound != true {
> ```

As per comment above: why not just return err (and conceivably rename `PasswordMatch`?

---

*[server/login.go, line 159 at r1](https://reviewable.io:443/reviews/sfbrigade/sfsbook/128#-KgJR0eYP_SDZo6l3yfd:-KgJR0eYP_SDZo6l3yfe:bl0zon1) ([raw file](https://github.com/sfbrigade/sfsbook/blob/62b2c67daab34b13f929eebc6120340f35d5fb72/server/login.go#L159)):*
> ```Go
> 			// I think this means that the user can't have a cookie.
> 			// i.e. we make a sad page.
> 			log.Println("ERROR: User can't haz no cookies?? ", err)
> ```

To the amusement of my team, I once wrote an API spec in lolspeak. :-)

---

*[server/login.go, line 164 at r1](https://reviewable.io:443/reviews/sfbrigade/sfsbook/128#-KgJRIqiJOmxyT0aDB5B:-KgJRIqiJOmxyT0aDB5C:b-83sjo4) ([raw file](https://github.com/sfbrigade/sfsbook/blob/62b2c67daab34b13f929eebc6120340f35d5fb72/server/login.go#L164)):*
> ```Go
> 
> 		log.Println("login worked, redirecting to index")
> 		http.Redirect(w, req, "/index.html", http.StatusFound)
> ```

Nice.

---

*[server/login_test.go, line 24 at r1](https://reviewable.io:443/reviews/sfbrigade/sfsbook/128#-KgJ_7_n7Buv7FMAHwwh:-KgJ_7_n7Buv7FMAHwwi:bewjicy) ([raw file](https://github.com/sfbrigade/sfsbook/blob/62b2c67daab34b13f929eebc6120340f35d5fb72/server/login_test.go#L24)):*
> ```Go
> 
>     // not secure (not random) but OK for testing
>     var hashKey = []byte("very-secret")
> ```

You could write this: `hashKey := []byte("very-secret")` instead? It would be more idiomatic.

---

*[server/login_test.go, line 44 at r1](https://reviewable.io:443/reviews/sfbrigade/sfsbook/128#-KgJaNrOxagEtxECV0_3:-KgJaNrOxagEtxECV0_4:b-tzfpdi) ([raw file](https://github.com/sfbrigade/sfsbook/blob/62b2c67daab34b13f929eebc6120340f35d5fb72/server/login_test.go#L44)):*
> ```Go
>     uuid := uuid.NewRandom()
>     defer testHelper()()
>     undertesthandler := makeMockServer(nil)
> ```

I'm confused here. Why is the tape nil?

---

*[server/mockpassword_test.go, line 47 at r1](https://reviewable.io:443/reviews/sfbrigade/sfsbook/128#-KgJan9ZOXk97EIPOtVW:-KgJan9ZOXk97EIPOtVX:bd1i9bh) ([raw file](https://github.com/sfbrigade/sfsbook/blob/62b2c67daab34b13f929eebc6120340f35d5fb72/server/mockpassword_test.go#L47)):*
> ```Go
> // You can search for anything,
> // but only (username,password := "test_user", "password") return a nonempty result
> func (tape *mockPasswordIndex) Search(username string) (dba.PasswordSearchResult, error) {
> ```

Shouldn't you update the tape here? The playback tape is the source of `PasswordSearchResult` objects while the record tape holds the `username` that we're searching for?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sfbrigade/sfsbook/128)*

**Comment by techieshark** [comment]
Review status: 3 of 4 files reviewed at latest revision, 10 unresolved discussions.

---

*[server/login.go, line 159 at r1](https://reviewable.io:443/reviews/sfbrigade/sfsbook/128#-KgJR0eYP_SDZo6l3yfd:-KgKwwhEKOvpjHmE-bYd:b17b0w8) ([raw file](https://github.com/sfbrigade/sfsbook/blob/62b2c67daab34b13f929eebc6120340f35d5fb72/server/login.go#L159)):*
<details><summary><i>Previously, rjkroege (Robert Kroeger) wrote…</i></summary><blockquote>

To the amusement of my team, I once wrote an API spec in lolspeak. :-)
</blockquote></details>

lolz ;) 

---

*[server/login_test.go, line 44 at r1](https://reviewable.io:443/reviews/sfbrigade/sfsbook/128#-KgJaNrOxagEtxECV0_3:-KgKsfbwWY8C0PNdTZPe:b-691iqv) ([raw file](https://github.com/sfbrigade/sfsbook/blob/62b2c67daab34b13f929eebc6120340f35d5fb72/server/login_test.go#L44)):*
<details><summary><i>Previously, rjkroege (Robert Kroeger) wrote…</i></summary><blockquote>

I'm confused here. Why is the tape nil?
</blockquote></details>

Good question -- tbh I just copied some of that test setup code from [usermgt_test.go](https://github.com/sfbrigade/sfsbook/blob/master/server/usermgt_test.go#L52). 

---

*[server/mockpassword_test.go, line 47 at r1](https://reviewable.io:443/reviews/sfbrigade/sfsbook/128#-KgJan9ZOXk97EIPOtVW:-KgKx6wus88Yj6gZ-Bzn:b-52pule) ([raw file](https://github.com/sfbrigade/sfsbook/blob/62b2c67daab34b13f929eebc6120340f35d5fb72/server/mockpassword_test.go#L47)):*
<details><summary><i>Previously, rjkroege (Robert Kroeger) wrote…</i></summary><blockquote>

Shouldn't you update the tape here? The playback tape is the source of `PasswordSearchResult` objects while the record tape holds the `username` that we're searching for?
</blockquote></details>

Another good question. Again any errors or strangeness about how I'm using tape is because I don't yet understand how it works / is supposed to work. Other than looking at the other code, I also looked at the tape package and the upstream Vanadium code but didn't spend a whole lot of time trying to figure it out (the comments in mock.go and the tests in mock_test.go are helpful but I'll have to play around with it a bit more I suppose).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sfbrigade/sfsbook/128)*

**Comment by techieshark** [comment]
Review status: 0 of 4 files reviewed at latest revision, 9 unresolved discussions.

---

*[dba/password_index.go, line 59 at r1](https://reviewable.io:443/reviews/sfbrigade/sfsbook/128#-KgJSmikTQTzPhJt_-ls:-KgS39eNukJUGjBCkNjy:b-896fix) ([raw file](https://github.com/sfbrigade/sfsbook/blob/62b2c67daab34b13f929eebc6120340f35d5fb72/dba/password_index.go#L59)):*
<details><summary><i>Previously, rjkroege (Robert Kroeger) wrote…</i></summary><blockquote>

Given `PasswordMatch()`, could `PasswordHash` be private (i.e. `passwordHash`)?
</blockquote></details>

Done.

---

*[dba/password_index.go, line 65 at r1](https://reviewable.io:443/reviews/sfbrigade/sfsbook/128#-KgJT11pcquK5cFGUB0q:-KgS3ApJewpj4DQxdLAk:b-896fix) ([raw file](https://github.com/sfbrigade/sfsbook/blob/62b2c67daab34b13f929eebc6120340f35d5fb72/dba/password_index.go#L65)):*
<details><summary><i>Previously, rjkroege (Robert Kroeger) wrote…</i></summary><blockquote>

I'd probably pass `psr` by reference? (i.e. `*PasswordSearchResult`) as passing it by value makes a temporary. But `PasswordSearchResult` instances aren't very big. So maybe it doesn't matter very much.
</blockquote></details>

Done.

---

*[dba/password_index.go, line 68 at r1](https://reviewable.io:443/reviews/sfbrigade/sfsbook/128#-KgJWjjKH-QroHY16B-I:-KgS3BOyWBh8mBh-YYoL:b-896fix) ([raw file](https://github.com/sfbrigade/sfsbook/blob/62b2c67daab34b13f929eebc6120340f35d5fb72/dba/password_index.go#L68)):*
<details><summary><i>Previously, rjkroege (Robert Kroeger) wrote…</i></summary><blockquote>

nit: why not just return `err`?
</blockquote></details>

Done.

---

*[dba/password_index.go, line 72 at r1](https://reviewable.io:443/reviews/sfbrigade/sfsbook/128#-KgJSK0zVrUr-JuKdUnj:-KgS3CMHLtaniKPF3TpG:b-896fix) ([raw file](https://github.com/sfbrigade/sfsbook/blob/62b2c67daab34b13f929eebc6120340f35d5fb72/dba/password_index.go#L72)):*
<details><summary><i>Previously, rjkroege (Robert Kroeger) wrote…</i></summary><blockquote>

The code could be more efficient if you returned a `*PasswordSearchResult`. And then `Found` would be unnecessary: simply return nil is nothing was found.
</blockquote></details>

Done.

---

*[dba/password_index.go, line 80 at r1](https://reviewable.io:443/reviews/sfbrigade/sfsbook/128#-KgJTMUV32ASgQH8Tmm1:-KgS3CucjnghEn5vqwZg:b-896fix) ([raw file](https://github.com/sfbrigade/sfsbook/blob/62b2c67daab34b13f929eebc6120340f35d5fb72/dba/password_index.go#L80)):*
<details><summary><i>Previously, rjkroege (Robert Kroeger) wrote…</i></summary><blockquote>

This isn't particularly idiomatic. Something more like:

```go
return &PasswordSearchResult {
  // fields initializers...
}
```

is more typical.
</blockquote></details>

Done.

---

*[server/login.go, line 111 at r1](https://reviewable.io:443/reviews/sfbrigade/sfsbook/128#-KgJUGN2InyphZ5cpnKB:-KgS3DmN0teXmxOqkeF2:b-896fix) ([raw file](https://github.com/sfbrigade/sfsbook/blob/62b2c67daab34b13f929eebc6120340f35d5fb72/server/login.go#L111)):*
<details><summary><i>Previously, rjkroege (Robert Kroeger) wrote…</i></summary><blockquote>

As per comment above: why not just return err (and conceivably rename `PasswordMatch`?
</blockquote></details>

Done.

---

*[server/login_test.go, line 24 at r1](https://reviewable.io:443/reviews/sfbrigade/sfsbook/128#-KgJ_7_n7Buv7FMAHwwh:-KgS3F5OU-QITGrS42ld:b-896fix) ([raw file](https://github.com/sfbrigade/sfsbook/blob/62b2c67daab34b13f929eebc6120340f35d5fb72/server/login_test.go#L24)):*
<details><summary><i>Previously, rjkroege (Robert Kroeger) wrote…</i></summary><blockquote>

You could write this: `hashKey := []byte("very-secret")` instead? It would be more idiomatic.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sfbrigade/sfsbook/128)*

**Comment by rjkroege** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[dba/password_index.go, line 66 at r2](https://reviewable.io:443/reviews/sfbrigade/sfsbook/128#-Kh_BYPLbC_ihMH8bdst:-Kh_BYPLbC_ihMH8bdsu:b-qate0w) ([raw file](https://github.com/sfbrigade/sfsbook/blob/043dffd0080b55253624e89069da6ddd4cb12dfa/dba/password_index.go#L66)):*
> ```Go
> }
> 
> // Construct a new PasswordSearchResult
> ```

valid godoc requires the method doc to start with 

```go
// NewPasswordSearchResult blah blah...
```

I'd prefer you to fix but maybe later if you'd like.

---

*[server/login.go, line 164 at r2](https://reviewable.io:443/reviews/sfbrigade/sfsbook/128#-Kh_D3RR-VlnZVTXIzHG:-Kh_D3RR-VlnZVTXIzHH:b-7m74ok) ([raw file](https://github.com/sfbrigade/sfsbook/blob/043dffd0080b55253624e89069da6ddd4cb12dfa/server/login.go#L164)):*
> ```Go
> 
> 		log.Println("login worked, redirecting to index")
> 		http.Redirect(w, req, "/index.html", http.StatusFound)
> ```

nice.

---

*[server/login_test.go, line 44 at r1](https://reviewable.io:443/reviews/sfbrigade/sfsbook/128#-KgJaNrOxagEtxECV0_3:-Kh_DBRda2IXY1UyS0bI:b9fdkf8) ([raw file](https://github.com/sfbrigade/sfsbook/blob/62b2c67daab34b13f929eebc6120340f35d5fb72/server/login_test.go#L44)):*
<details><summary><i>Previously, techieshark (Peter W) wrote…</i></summary><blockquote>

Good question -- tbh I just copied some of that test setup code from [usermgt_test.go](https://github.com/sfbrigade/sfsbook/blob/master/server/usermgt_test.go#L52). 
</blockquote></details>

Then the test isn't really validating that the right requests were sent to the mock dba layer. Maybe we should discuss.

---

*[server/mockpassword_test.go, line 47 at r1](https://reviewable.io:443/reviews/sfbrigade/sfsbook/128#-KgJan9ZOXk97EIPOtVW:-Kh_DTUIEDPw_9-Jfxn2:b-wc5361) ([raw file](https://github.com/sfbrigade/sfsbook/blob/62b2c67daab34b13f929eebc6120340f35d5fb72/server/mockpassword_test.go#L47)):*
<details><summary><i>Previously, techieshark (Peter W) wrote…</i></summary><blockquote>

Another good question. Again any errors or strangeness about how I'm using tape is because I don't yet understand how it works / is supposed to work. Other than looking at the other code, I also looked at the tape package and the upstream Vanadium code but didn't spend a whole lot of time trying to figure it out (the comments in mock.go and the tests in mock_test.go are helpful but I'll have to play around with it a bit more I suppose).
</blockquote></details>

I will attempt to explain.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sfbrigade/sfsbook/128)*

**Comment by rjkroege** [comment]
tape stuff to be updated later? if so, :lgtm: 

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sfbrigade/sfsbook/128#-:-Kj30UL7L49J2DRYzzWy:b8z51kc)*

**Comment by rjkroege** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[server/login_test.go, line 44 at r1](https://reviewable.io:443/reviews/sfbrigade/sfsbook/128#-KgJaNrOxagEtxECV0_3:-KjbcxLOncTRRWDDFJFB:b-7ckbkd) ([raw file](https://github.com/sfbrigade/sfsbook/blob/62b2c67daab34b13f929eebc6120340f35d5fb72/server/login_test.go#L44)):*
<details><summary><i>Previously, rjkroege (Robert Kroeger) wrote…</i></summary><blockquote>

Then the test isn't really validating that the right requests were sent to the mock dba layer. Maybe we should discuss.
</blockquote></details>

We did discuss? Were you going to fix now or perhaps update in a different CL? You can look at `editusers_test.go` and `listusers_test.go` for some way more complicated use of the tape library. You could consider adding a `TODO` here for me instead.

---

*[server/mockpassword_test.go, line 47 at r1](https://reviewable.io:443/reviews/sfbrigade/sfsbook/128#-KgJan9ZOXk97EIPOtVW:-KjbdTu1s_0oR-nG-jCn:bl43ocw) ([raw file](https://github.com/sfbrigade/sfsbook/blob/62b2c67daab34b13f929eebc6120340f35d5fb72/server/mockpassword_test.go#L47)):*
<details><summary><i>Previously, rjkroege (Robert Kroeger) wrote…</i></summary><blockquote>

I will attempt to explain.
</blockquote></details>

I attempted to explain. What's your thinking here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sfbrigade/sfsbook/128)*

**Pull request closed without merging**
