### PR TITLE
Basic styling

### PR DESCRIPTION
**Pull request by cehsu**
This change is [Reviewable](https://reviewable.io/reviews/sfbrigade/sfsbook/90)

### CODE REVIEW

**Comment by rjkroege** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[site/index.html, line 20 at r1](https://reviewable.io:443/reviews/sfbrigade/sfsbook/90#-KYR9XOkQEYMemadv4VA:-KYR9XOkQEYMemadv4VB:b-gx6nj3) ([raw file](https://github.com/sfbrigade/sfsbook/blob/9fcd3a04d7d133d3cc10db530348e081f27a1688/site/index.html#L20)):*
> ```HTML
> 		<ul>
> 			<li class="category-option">
> 				<input type="checkbox" name="location" value="Oakland">Oakland<br>
> ```

we don't have back-end support for this right? you should file a bug against me.

---

*[site/index.html, line 37 at r1](https://reviewable.io:443/reviews/sfbrigade/sfsbook/90#-KYR9HWZ80ygAWcKDUrx:-KYR9HWZ80ygAWcKDUry:bgxrm03) ([raw file](https://github.com/sfbrigade/sfsbook/blob/9fcd3a04d7d133d3cc10db530348e081f27a1688/site/index.html#L37)):*
> ```HTML
>                 <ul>
> 			<li class="category-option">                      
> 				<input type="c
> ```

this seems like weird line breaking? here and above?

---

*[site/css/style.css, line 2 at r1](https://reviewable.io:443/reviews/sfbrigade/sfsbook/90#-KYR9QV5PCSpjEoYUH_v:-KYR9QV5PCSpjEoYUH_w:bdoza0o) ([raw file](https://github.com/sfbrigade/sfsbook/blob/9fcd3a04d7d133d3cc10db530348e081f27a1688/site/css/style.css#L2)):*
> ```CSS
> /*
> 	Colour is only to demonstrate that I have working CSS support.
> ```

this comment is obsolete. you could remove?

---

*[site/css/style.css, line 26 at r1](https://reviewable.io:443/reviews/sfbrigade/sfsbook/90#-KYTjJFx_fcJ30Go53wH:-KYTjJFx_fcJ30Go53wI:b-wzb8bd) ([raw file](https://github.com/sfbrigade/sfsbook/blob/9fcd3a04d7d133d3cc10db530348e081f27a1688/site/css/style.css#L26)):*
> ```CSS
>     	width: 25%; }
> 	.header-section:nth-child(1) {
>                 float: left; }
> ```

you don't use white space consistently here. should we have a linter for css? Is there one you like?

---

*[site/js/searchbar.js, line 3 at r1](https://reviewable.io:443/reviews/sfbrigade/sfsbook/90#-KYR9ibA1-w7FBjh2K7m:-KYR9ibA1-w7FBjh2K7n:blv6wwe) ([raw file](https://github.com/sfbrigade/sfsbook/blob/9fcd3a04d7d133d3cc10db530348e081f27a1688/site/js/searchbar.js#L3)):*
> ```JavaScript
> // Searchbar JavaScript code for sfsbook
> 
> // toggleCategoryOption adds or removes a keyword from the search
> ```

You modify the search box based on the picker? That's clever.

---

*[site/js/searchbar.js, line 14 at r1](https://reviewable.io:443/reviews/sfbrigade/sfsbook/90#-KYTjWIXk0BNxaOoA57z:-KYTjWIXk0BNxaOoA58-:byrfuo2) ([raw file](https://github.com/sfbrigade/sfsbook/blob/9fcd3a04d7d133d3cc10db530348e081f27a1688/site/js/searchbar.js#L14)):*
> ```JavaScript
> 			searchText = searchText.replace(stringToReplace, "");
> 			el.value = searchText;
> 		} else if (searchText.match(re)) {
> ```

this indenting is weird? I think we definitely need some kind of JS linter / formatter? Do you have a style guide preference for JS? I am biased towards http://google.github.io/styleguide/jsguide.html based on past experience. But that suggests that there should be some kind of formatter. I'll look into it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sfbrigade/sfsbook/90)*

**Comment by cehsu** [comment]
Review status: 2 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[site/css/style.css, line 2 at r1](https://reviewable.io:443/reviews/sfbrigade/sfsbook/90#-KYR9QV5PCSpjEoYUH_v:-KZ2YUatDr2WMTFnidHB:b-896fix) ([raw file](https://github.com/sfbrigade/sfsbook/blob/9fcd3a04d7d133d3cc10db530348e081f27a1688/site/css/style.css#L2)):*
<details><summary><i>Previously, rjkroege (Robert Kroeger) wrote…</i></summary><blockquote>

this comment is obsolete. you could remove?
</blockquote></details>

Done.

---

*[site/css/style.css, line 26 at r1](https://reviewable.io:443/reviews/sfbrigade/sfsbook/90#-KYTjJFx_fcJ30Go53wH:-KZ2YWneZksroLN_9kIM:b-896fix) ([raw file](https://github.com/sfbrigade/sfsbook/blob/9fcd3a04d7d133d3cc10db530348e081f27a1688/site/css/style.css#L26)):*
<details><summary><i>Previously, rjkroege (Robert Kroeger) wrote…</i></summary><blockquote>

you don't use white space consistently here. should we have a linter for css? Is there one you like?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sfbrigade/sfsbook/90)*

**Comment by cehsu** [comment]
Review status: 2 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[site/index.html, line 20 at r1](https://reviewable.io:443/reviews/sfbrigade/sfsbook/90#-KYR9XOkQEYMemadv4VA:-KZ2Yz26VoeBWrOdxHEM:b-896fix) ([raw file](https://github.com/sfbrigade/sfsbook/blob/9fcd3a04d7d133d3cc10db530348e081f27a1688/site/index.html#L20)):*
<details><summary><i>Previously, rjkroege (Robert Kroeger) wrote…</i></summary><blockquote>

we don't have back-end support for this right? you should file a bug against me.
</blockquote></details>

Done.

---

*[site/index.html, line 37 at r1](https://reviewable.io:443/reviews/sfbrigade/sfsbook/90#-KYR9HWZ80ygAWcKDUrx:-KZ2Yy407zNsFyjOYRf3:b-896fix) ([raw file](https://github.com/sfbrigade/sfsbook/blob/9fcd3a04d7d133d3cc10db530348e081f27a1688/site/index.html#L37)):*
<details><summary><i>Previously, rjkroege (Robert Kroeger) wrote…</i></summary><blockquote>

this seems like weird line breaking? here and above?
</blockquote></details>

Done.

---

*[site/js/searchbar.js, line 3 at r1](https://reviewable.io:443/reviews/sfbrigade/sfsbook/90#-KYR9ibA1-w7FBjh2K7m:-KZ2YulGKjSIad_qwVaA:b-896fix) ([raw file](https://github.com/sfbrigade/sfsbook/blob/9fcd3a04d7d133d3cc10db530348e081f27a1688/site/js/searchbar.js#L3)):*
<details><summary><i>Previously, rjkroege (Robert Kroeger) wrote…</i></summary><blockquote>

You modify the search box based on the picker? That's clever.
</blockquote></details>

Done.

---

*[site/js/searchbar.js, line 14 at r1](https://reviewable.io:443/reviews/sfbrigade/sfsbook/90#-KYTjWIXk0BNxaOoA57z:-KZ2YuLI20TNHwkSLl7o:b-896fix) ([raw file](https://github.com/sfbrigade/sfsbook/blob/9fcd3a04d7d133d3cc10db530348e081f27a1688/site/js/searchbar.js#L14)):*
<details><summary><i>Previously, rjkroege (Robert Kroeger) wrote…</i></summary><blockquote>

this indenting is weird? I think we definitely need some kind of JS linter / formatter? Do you have a style guide preference for JS? I am biased towards http://google.github.io/styleguide/jsguide.html based on past experience. But that suggests that there should be some kind of formatter. I'll look into it.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sfbrigade/sfsbook/90)*

**Comment by cehsu** [comment]
Reviewed 1 of 5 files at r1.
Review status: 2 of 6 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sfbrigade/sfsbook/90)*

**Comment by cehsu** [comment]
Reviewed 2 of 5 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sfbrigade/sfsbook/90)*

**Comment by rjkroege** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[site/index.html, line 37 at r1](https://reviewable.io:443/reviews/sfbrigade/sfsbook/90#-KYR9HWZ80ygAWcKDUrx:-KZCyg2-jTe6gKErOha1:bn8wnbc) ([raw file](https://github.com/sfbrigade/sfsbook/blob/9fcd3a04d7d133d3cc10db530348e081f27a1688/site/index.html#L37)):*
<details><summary><i>Previously, cehsu (Claire Hsu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Maybe I'm not reading the tool correctly but don't you have a newline after the `input type=c`? That's what I was observing. That doesn't seem right?

Anyway, I'm OK with this. Later, we'll have some kind of linter thing.

---

*[site/search.html, line 16 at r2](https://reviewable.io:443/reviews/sfbrigade/sfsbook/90#-KZCz0XWYpd2gGr9pz_t:-KZCz0XWYpd2gGr9pz_u:b9vjfz4) ([raw file](https://github.com/sfbrigade/sfsbook/blob/8be09818a6608dbdef47653cd45c858cdf6ecbb3/site/search.html#L16)):*
> ```HTML
>         <a href="#">Locations</a>
>                 <ul>
>                         <li class="category-option">
> ```

I think that I need to configure this tool to show indents differently.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sfbrigade/sfsbook/90#-:-KZCzfiUG14IRXvnp70t:bnfp4nl)*

**Comment by rjkroege** [comment]
Reviewed 2 of 4 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sfbrigade/sfsbook/90)*

**Pull request merged**
