### PR TITLE
update readme with more instructions

### PR DESCRIPTION
**Pull request by sent-hil**
This change is [Reviewable](https://reviewable.io/reviews/sfbrigade/sfsbook/167)

### CODE REVIEW

**Comment by SYU15** [comment]
Great update, thanks!

**Comment by cehsu** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 53 at r1](https://reviewable.io:443/reviews/sfbrigade/sfsbook/167#-KszOpevFFPfRiS75dAf:-KszOpewE6KWzvAtBbPs:b-oy9hw6) ([raw file](https://github.com/sfbrigade/sfsbook/blob/9f5df637de1f9e1f426cf908a5a2d846806f359f/README.md#L53)):*
> ```Markdown
> 
>     go get -u github.com/kardianos/govendor
>     govendor add +external
> ```

Should we also remind contributors to make sure that they include the new vendor bundle in their PR (as this is atypical)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sfbrigade/sfsbook/167)*

**Comment by cehsu** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sfbrigade/sfsbook/167#-:-KszPEFDmLMAdIVlpt-2:bnfp4nl)*

**Comment by sent-hil** [comment]
@cehsu updated!

**Pull request closed without merging**
