### PR TITLE
on successful login, jump back to index page

### LINKED ISSUE #117: reroute to index on successful log in

### PR DESCRIPTION
**Pull request by techieshark**
Fixes #117

* Not sure if HTTP 302 is the right redirect code, but it works.
* Paired with @mwillcox, so don't blame me if this breaks. ;)

### CODE REVIEW

**Comment by cehsu** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sfbrigade/sfsbook/125)*

**Comment by rjkroege** [comment]
Perhaps there could be a test for this?

**Comment by techieshark** [comment]
@rjkroege sure. I'm new to Go, so any advice on getting started is welcome. I guessed at how to run the tests we have now, but I think I guessed wrong:

```
 ~ > ... > sfsbook > server $ go test
# github.com/sfbrigade/sfsbook/server
mockpassword_test.go:8:2: cannot find package "github.com/rjkroege/mocking" in any of:
	/Users/peter/go/src/github.com/sfbrigade/sfsbook/vendor/github.com/rjkroege/mocking (vendor tree)
	/usr/local/Cellar/go/1.8/libexec/src/github.com/rjkroege/mocking (from $GOROOT)
	/Users/peter/go/src/github.com/rjkroege/mocking (from $GOPATH)
FAIL	github.com/sfbrigade/sfsbook/server [setup failed]
```

Is there a trick to get `go get` to look at the test files and download whatever packages it needs?

**Comment by techieshark** [comment]
update: I see that I can manually do it via `go get github.com/rjkroege/mocking; go test` but I'm still curious if I'm missing the automatic way to have go figure it out.

**Comment by techieshark** [comment]
I'm thinking we could add some documentation on running tests to the README. Useful to reduce friction for new developers -- something like (but open to improvements):

## Testing

To run the code tests:

```
cd server
go get github.com/rjkroege/mocking # just the first time
go test
```

You can also test just one file by passing the filename to `go test`:

```
cd server
go get github.com/rjkroege/mocking # just the first time
go test usermgt_test.go
```

**Comment by rjkroege** [comment]
The missing dependency on `mocking` is my fault. I didn't vendor my own testing package into the project.  You might want to learn about Go vendoring. There doesn't seem to be a README about it but I'm sure that I wrote something down about the process. Maybe in the comments to a bug.

To run the tests, to to the top level and run `go test ./...` to run all of them. If you run the tests in the `server` directory, you won't be running all of the tests. Look at the travis configuration to see how we run the tests on the builders.

**Comment by rjkroege** [comment]
So I blithered about vendoring in the slack channel but didn't really right anything useful. I will add something to the README after I've reminded myself how I set this up. Anyway, the `go get` for missing dependencies is the right short term thing to do.

**Pull request merged**
