### PR TITLE
Update README.md for hiatus

### PR DESCRIPTION
**Pull request by rjkroege**
Note that project is on hiatus in the README

---
This change is [Reviewable](https://reviewable.io/reviews/sfbrigade/sfsbook/168)

### CODE REVIEW

**Comment by techieshark** [comment]
@sent-hil what's the status of this? @cehsu had a meeting right?

**Comment by greggish** [comment]
I encourage y'all to connect with the Service Net initiative, involving multiple referral providers and resource directory maintainers across the Bay Area. [Read more here](https://benetech.org/lab/access-social-services/), see [notes from their convening here](https://docs.google.com/document/d/1LHdHyoRbFESZ2Ou4lKVhN7HHfMuqkFHE4tKKFL32Uik/edit#), and [check out a webinar covering the highlights here](https://www.youtube.com/watch?v=mGrjWBxuPsM).

**Comment by sent-hil** [comment]
we're back to actively working on this again

**Comment by sent-hil** [comment]
thanks @greggish, will look into it

**Pull request closed without merging**
